sonarqube:
  image: sonarqube:5.1.1
  ports:
   - "9000:9000"
   - "3306:3306"
  environment:
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
   - SONARQUBE_JDBC_URL=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

db:
  image: mysql
  net: container:sonarqube
  environment:
   - MYSQL_ROOT_PASSWORD=sonar
   - MYSQL_DATABASE=sonar
   - MYSQL_USER=sonar
   - MYSQL_PASSWORD=sonar
